version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'cloud-file-storage-postgresql-database'
    environment:
      - 'POSTGRES_DB=cfsdb'
      - 'POSTGRES_PASSWORD=yukir'
      - 'POSTGRES_USER=yukir'
    ports:
      - '6380:5432'

  redis:
    image: 'redis:latest'
    container_name: 'cloud-file-storage-redis-database'
    ports:
      - '6379:6379'  
