server:
  servlet:
    session:
      cookie:
        max-age: 1296000

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Cloud-File-Storage
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    name: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
